provider:
  name: aws
  runtime: java8
  
package:
  artifact: build/distributions/aws-lib-java-lambda-function.zip

Type: AWS::Serverless::Function
Properties:
  Handler: com.serverless.LambdaHandler
  CodeUri: ./build/distributions/aws-lib-java-lambda-function.zip
  Runtime: java8
  Events:
    Api:
      Type: Api
      Properties:
        Path: /test
        Method: get
