AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  TestLibLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.serverless.LambdaHandler
      CodeUri: ./target/aws-lib-java-lambda-function.jar
      Runtime: java8
      Timeout: 300
      Policies: AWSLambdaFullAccess
      Events:
        UploadFilesEvent:
          Type: S3
          Properties:
            Id: !Ref Bucket
            Events: Create
  Bucket:
    Type: AWS::S3::Bucket